%~dp0nuget.exe pack %~dp0CuteAnt.Extensions.Serialization.Abstractions.nuspec -OutputDirectory Publish
%~dp0nuget.exe pack %~dp0CuteAnt.Extensions.Serialization.Bond.nuspec -OutputDirectory Publish
%~dp0nuget.exe pack %~dp0CuteAnt.Extensions.Serialization.nuspec -OutputDirectory Publish
%~dp0nuget.exe pack %~dp0CuteAnt.Extensions.Serialization.Protobuf.nuspec -OutputDirectory Publish
%~dp0nuget.exe pack %~dp0CuteAnt.IO.RecyclableMemoryStream.nuspec -OutputDirectory Publish
%~dp0nuget.exe pack %~dp0CuteAnt.Osin.ConsoleHost.nuspec -OutputDirectory Publish
%~dp0nuget.exe pack %~dp0CuteAnt.Osin.nuspec -OutputDirectory Publish
%~dp0nuget.exe pack %~dp0CuteAnt.Osin.ServerEngine.Abstractions.nuspec -OutputDirectory Publish
%~dp0nuget.exe pack %~dp0CuteAnt.Osin.ServerEngine.nuspec -OutputDirectory Publish
%~dp0nuget.exe pack %~dp0CuteAnt.Osin.ServiceHost.nuspec -OutputDirectory Publish
%~dp0nuget.exe pack %~dp0CuteAnt.Runtime.nuspec -OutputDirectory Publish
%~dp0nuget.exe pack %~dp0CuteAnt.Utils.nuspec -OutputDirectory Publish
%~dp0nuget.exe pack %~dp0CuteAnt.Wings.AzureUtils.nuspec -OutputDirectory Publish
%~dp0nuget.exe pack %~dp0CuteAnt.Wings.Client.nuspec -OutputDirectory Publish
%~dp0nuget.exe pack %~dp0CuteAnt.Wings.CodeGenerator.nuspec -OutputDirectory Publish
%~dp0nuget.exe pack %~dp0CuteAnt.Wings.CodeGenerator.Build.nuspec -OutputDirectory Publish
%~dp0nuget.exe pack %~dp0CuteAnt.Wings.ConsoleHost.nuspec -OutputDirectory Publish
%~dp0nuget.exe pack %~dp0CuteAnt.Wings.ConsulUtils.nuspec -OutputDirectory Publish
%~dp0nuget.exe pack %~dp0CuteAnt.Wings.CounterControl.nuspec -OutputDirectory Publish
%~dp0nuget.exe pack %~dp0CuteAnt.Wings.EventSourcing.nuspec -OutputDirectory Publish
%~dp0nuget.exe pack %~dp0CuteAnt.Wings.Manager.nuspec -OutputDirectory Publish
%~dp0nuget.exe pack %~dp0CuteAnt.Wings.nuspec -OutputDirectory Publish
%~dp0nuget.exe pack %~dp0CuteAnt.Wings.Providers.nuspec -OutputDirectory Publish
%~dp0nuget.exe pack %~dp0CuteAnt.Wings.Runtime.nuspec -OutputDirectory Publish
%~dp0nuget.exe pack %~dp0CuteAnt.Wings.Server.nuspec -OutputDirectory Publish
%~dp0nuget.exe pack %~dp0CuteAnt.Wings.ServiceBus.nuspec -OutputDirectory Publish
%~dp0nuget.exe pack %~dp0CuteAnt.Wings.ServiceHost.nuspec -OutputDirectory Publish
%~dp0nuget.exe pack %~dp0CuteAnt.Wings.SqlUtils.nuspec -OutputDirectory Publish
%~dp0nuget.exe pack %~dp0CuteAnt.Wings.TestingHost.nuspec -OutputDirectory Publish
%~dp0nuget.exe pack %~dp0CuteAnt.Wings.ZooKeeperUtils.nuspec -OutputDirectory Publish
%~dp0nuget.exe pack %~dp0protobuf-net.nuspec -OutputDirectory Publish
%~dp0nuget.exe pack %~dp0SuperSocket.Common.nuspec -OutputDirectory Publish
%~dp0nuget.exe pack %~dp0SuperSocket.SocketBase.nuspec -OutputDirectory Publish
%~dp0nuget.exe pack %~dp0SuperSocket.SocketEngine.nuspec -OutputDirectory Publish
